#!/bin/sh
#inkVerbDroid! verb.ink

# This installs Armadillo libraries for Qt in Ubuntu
## You must run this as sudo

# Armadillo, LAPACK and BLAS is already installed. Just remember to link to these. In Qt Creator, just add the following line to your .pro file:
## `LIBS += -llapack -lblas -larmadillo`

# How to use:
## sudo ./vdarmadilloqt


# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./vdarmadilloqt
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./vdarmadilloqt
"
exit 22
fi

# Install it
apt install liblapack-dev libblas-dev libboost-dev libarmadillo-dev cmake

# Finish
echo "Done."






